Repository AY2223S2-CS2103T-T14-3/tp, pull requests merged in 2023-04, with the labels that each got.

#187 fix ug bugs
  docs/UserGuide.md
Labels: bug, documentation

#190 Update ppp
  docs/team/seadragon2000341.md
Labels: documentation, priority.High

#192 Update Eugene's PPP
  docs/team/eugenetangkj.md
Labels: documentation, priority.High

#193 Add tests
  src/test/java/seedu/internship/logic/LogicManagerTest.java
  src/test/java/seedu/internship/logic/commands/CommandResultTest.java
  src/test/java/seedu/internship/logic/commands/CommandTestUtil.java
  src/test/java/seedu/internship/logic/commands/DeleteIndexCommandTest.java
  src/test/java/seedu/internship/logic/commands/EditCommandTest.java
  src/test/java/seedu/internship/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/internship/model/InternBuddyTest.java
  src/test/java/seedu/internship/model/internship/CommentTest.java
  src/test/java/seedu/internship/model/internship/StatusTest.java
  src/test/java/seedu/internship/model/tag/TagTest.java
Labels: type.Enhancement, priority.Medium, test

#195 Fix errors in UG
  docs/UserGuide.md
Labels: documentation, priority.Low

#196 Fix dg bug
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: bug, documentation, priority.High

#198 Branch add tests
  docs/team/potty10.md
  src/main/java/seedu/internship/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/internship/logic/parser/FindCommandParser.java
  src/main/java/seedu/internship/logic/parser/ParserUtil.java
  src/test/java/seedu/internship/ui/CommandBoxTest.java
Labels: refactor, test

#197 Check 1: Update Developer Guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/gui-markup.png
  docs/index.md
Labels: documentation, priority.High

#200 Update Christopher's PPP
  docs/team/potty10.md
Labels: documentation, priority.High

#202 Update ug past commands find
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/dg-int-overflow-problem.png
  docs/images/dg-int-overflow-solution.png
  docs/images/dg-negative-int-overflow-solved.png
  docs/images/dg-positive-int-overflow-solved.png
  docs/images/ug-find-example.png
  docs/images/ug-navigate-commands.png
Labels: documentation, priority.High

#203 Update dg find diagram
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/team/kohkaixun.md
Labels: documentation

#206 V1.4 update Chuhao's ppp
  docs/team/derricksaltfish.md
Labels: documentation

#205 V1.4 update developer guide for command `Copy`
  docs/DeveloperGuide.md
  docs/diagrams/CopySequenceDiagram.puml
  docs/images/CopySequenceDiagram.png
Labels: documentation

#208 update ug
  docs/UserGuide.md
Labels: documentation, priority.High

#201 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteFieldSequenceDiagram.puml
  docs/diagrams/DeleteIndexSequenceDiagram.puml
  docs/images/DeleteFieldSequenceDiagram.png
  docs/images/DeleteIndexSequenceDiagram.png
  docs/images/dg-case-insensitive-add-after.png
  docs/images/dg-case-insensitive-add-before.png
  docs/images/dg-case-insensitive-prefix-fix.png
  docs/images/dg-case-sensitive-find-after.png
  docs/images/dg-case-sensitive-find-before.png
  docs/images/dg-case-sensitive-prefix-add-example.png
Labels: documentation, priority.High

#214 Final Check: README and Index.md
  README.md
  docs/AboutUs.md
  docs/index.md
  docs/team/eugenetangkj.md
  src/main/java/seedu/internship/MainApp.java
  src/main/java/seedu/internship/logic/Logic.java
  src/main/java/seedu/internship/logic/commands/AddCommand.java
  src/main/java/seedu/internship/logic/commands/ClearCommand.java
  src/main/java/seedu/internship/logic/commands/EditCommand.java
  src/main/java/seedu/internship/logic/commands/ExitCommand.java
  src/main/java/seedu/internship/logic/commands/FindCommand.java
  src/main/java/seedu/internship/logic/commands/ListCommand.java
  src/main/java/seedu/internship/model/InternBuddy.java
  src/main/java/seedu/internship/model/Model.java
  src/main/java/seedu/internship/model/ModelManager.java
  src/main/java/seedu/internship/model/ReadOnlyInternBuddy.java
  src/main/java/seedu/internship/model/internship/CompanyName.java
  src/main/java/seedu/internship/storage/JsonAdaptedInternship.java
  src/main/java/seedu/internship/storage/JsonSerializableInternBuddy.java
  src/main/java/seedu/internship/ui/InternshipCard.java
  src/test/java/seedu/internship/commons/core/index/IndexTest.java
  src/test/java/seedu/internship/logic/commands/CommandTestUtil.java
  src/test/java/seedu/internship/logic/commands/DeleteIndexCommandTest.java
  src/test/java/seedu/internship/logic/commands/EditCommandTest.java
  src/test/java/seedu/internship/model/internship/InternshipContainsKeywordsPredicateTest.java
  src/test/java/seedu/internship/model/internship/InternshipTest.java
  src/test/java/seedu/internship/storage/JsonInternBuddyStorageTest.java
Labels: documentation, type.Enhancement, priority.High

#204 Final Check: User Guide
  docs/UserGuide.md
Labels: documentation, priority.High, release

#215 Add editable diagram ppt
  docs/images/InternBuddy GUI Markup.pptx
Labels: documentation

#218 Update ppp
  docs/team/kohkaixun.md
Labels: documentation

#216 Final changes
  docs/images/dg-int-overflow-solution.png
  src/main/java/seedu/internship/logic/parser/CopyCommandParser.java
  src/main/java/seedu/internship/logic/parser/DeleteIndexCommandParser.java
  src/main/java/seedu/internship/logic/parser/EditCommandParser.java
  src/main/java/seedu/internship/logic/parser/ParserUtil.java
  src/main/java/seedu/internship/logic/parser/ViewCommandParser.java
Labels: documentation, refactor

#220 Final updates
  docs/UserGuide.md
  docs/team/derricksaltfish.md
Labels: documentation, priority.High

#221 Update design tweak in DG
  docs/DeveloperGuide.md
Labels: documentation

#223 Update PPP
  docs/team/potty10.md
Labels: documentation

#222 v1.4 Release
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/internship/MainApp.java
  src/test/java/seedu/internship/MainAppTest.java
Labels: priority.High, release

#225 Fix Capitalisation of Section Titles in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, type.Enhancement, priority.Medium

#226 Remove extra line break
  docs/DeveloperGuide.md
Labels: documentation, type.Enhancement, priority.Medium

#227 Add hyperlink in introduction
  docs/DeveloperGuide.md
Labels: documentation, type.Enhancement, priority.Low

#230 Fix numbering typo in appendix
  docs/DeveloperGuide.md
  docs/diagrams/CopyActivityDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
Labels: documentation, Type.Bug, priority.High
