Repository AY2223S2-CS2103T-T14-3/tp, pull requests merged in 2023-03, with the labels that each got.

#25 Update Christopher's PPP
  docs/team/potty10.md
Labels: team information

#21 Complete write-up for add command in user guide
  docs/UserGuide.md
Labels: documentation

#23 Add user stories to developer guide
  docs/DeveloperGuide.md
Labels: documentation

#24 Update DG for use cases add entry, exit application
  docs/DeveloperGuide.md
Labels: documentation

#26 Update User Guide
  docs/UserGuide.md
Labels: documentation

#22 Update User Guide
  docs/UserGuide.md
Labels: documentation

#28 Update Save and Edit data of user guide
  docs/UserGuide.md
Labels: documentation

#29 Update aboutus
  docs/AboutUs.md
  docs/images/derricksaltfish.png
Labels: documentation

#30 Update DG list edit
  .gitignore
  docs/DeveloperGuide.md
Labels: documentation

#31 Update Developer's Guide
  docs/DeveloperGuide.md
Labels: documentation

#32 Update UG list delete
  docs/UserGuide.md
Labels: documentation

#33 Update ppp for developer Ou Chuhao
  docs/_config.yml
  docs/index.md
  docs/team/derricksaltfish.md
Labels: documentation

#35 Add PPP
  docs/team/kohkaixun.md
Labels: documentation

#34 Finalise changes to user and developer guides for v1.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#38 Stricter date validation
  src/main/java/seedu/address/model/internship/Date.java
  src/test/java/seedu/address/model/internship/DateTest.java
Labels: bug

#50 Extend find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/internship/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/internship/InternshipContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internship/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/InternshipContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#51 Update some commands on User Guide
  docs/UserGuide.md
  docs/images/Clear-entries-warning-message.png
  docs/images/Edit_data_warning_message.png
Labels: documentation

#49 Update tests for Status
  docs/UserGuide.md
  src/test/java/seedu/address/model/internship/StatusTest.java
Labels: documentation

#52 Update UI
  build.gradle
  docs/images/Ui.png
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/seedu/address/ui/InternshipCardTest.java
  src/test/java/seedu/address/ui/StageExtension.java
  src/test/java/seedu/address/ui/UiPartExtension.java
Labels: type.Enhancement, priority.Low

#58 Update find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/internship/InternshipContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internship/InternshipContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#78 Implement View Command and Right Panel
  docs/images/internbuddy-hero.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/InternBuddyParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/InternBuddy.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/internship/UniqueInternshipList.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/InternshipDetailsCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/light_bulb.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipDetailsCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/address/ui/InternshipCardTest.java
  src/test/java/seedu/address/ui/InternshipDetailsCardTest.java
Labels: type.Enhancement, priority.High

#79 Feature to include Comments
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/Comment.java
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/java/seedu/address/ui/InternshipDetailsCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipDetailsCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableInternBuddyTest/duplicateInternshipInternBuddy.json
  src/test/data/JsonSerializableInternBuddyTest/invalidInternshipInternBuddy.json
  src/test/data/JsonSerializableInternBuddyTest/typicalInternshipInternBuddy.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/internship/CommentTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/InternshipUtil.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
  src/test/java/seedu/address/ui/InternshipDetailsCardTest.java
Labels: type.story, priority.High

#81 Fix Help Window UI
  docs/images/internbuddy-help.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium

#80 Update Developer Guide for edit
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
Labels: documentation, priority.High

#82 Write up the implementation for Add command in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: documentation, priority.High

#84 Write up the implementation for View command in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
Labels: documentation, priority.Medium

#87 Change labels and statuses
  src/main/java/seedu/address/model/internship/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/InternshipDetailsCard.java
  src/test/java/seedu/address/model/internship/StatusTest.java
  src/test/java/seedu/address/ui/InternshipCardTest.java
  src/test/java/seedu/address/ui/InternshipDetailsCardTest.java
Labels: type.Enhancement, priority.Medium

#88 Update DG Find Command
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: documentation

#89 Find by date
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/InternshipContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternBuddyParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/internship/InternshipContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#90 Update find uml sequence diagram
  build.gradle
  docs/diagrams/FindSequenceDiagram.puml
Labels: documentation

#93 Add upcoming command
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
  src/main/java/seedu/address/logic/parser/InternBuddyParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/UpcomingCommandTest.java
  src/test/java/seedu/address/testutil/TypicalInternshipsVariableDates.java
Labels: type.Enhancement, priority.Medium

#94 Edit UML diagram for EditSequenceDiagram
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
Labels: documentation

#95 Add logger for FindCommandParser and update find sequence diagram
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: documentation

#91 Prepare v1.3.1 jar file
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/internbuddy-help.png
  src/main/resources/images/internbuddy-hero.png
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/ui/InternshipCardTest.java
Labels: release

#99 V1.3-DeveloperGuide-update
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#98 Add logging and assertions
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: Type.task, priority.High

#101 update ug
  docs/UserGuide.md
Labels: documentation, priority.High

#102 Update user guide
  docs/UserGuide.md
  docs/images/gui-markup.png
Labels: documentation, priority.High

#105 update dg appendix B
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#106 Update About DG in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#107 Update set up and get started in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#119 Update User and Developer Guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/Ui.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/ug-add-example.png
  docs/images/ug-appendix-b-json-change.png
  docs/images/ug-appendix-b-json-example.png
  docs/images/ug-help-window.png
  docs/images/ug-view-example.png
Labels: documentation, priority.High

#120 update ug for edit and upcoming command
  docs/UserGuide.md
Labels: documentation

#122 Branch update dg upcoming
  docs/DeveloperGuide.md
  docs/diagrams/UpcomingSequenceDiagram.puml
  docs/images/UpcomingSequenceDiagram.png
Labels: documentation, priority.High

#123 Update ug dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ug-find-example.png
Labels: documentation

#124 Fix Equality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/Role.java
  src/test/java/seedu/address/model/InternBuddyTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
Labels: Type.task, priority.High

#126 update constraints
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Role.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/internship/CompanyNameTest.java
  src/test/java/seedu/address/model/internship/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
Labels: type.Enhancement, priority.High

#128 Fix right panel not resetting after clear
  src/main/java/seedu/internship/logic/commands/ClearCommand.java
Labels: bug, priority.High

#130 V1.3b copy command update
  docs/UserGuide.md
  src/main/java/seedu/internship/logic/commands/CopyCommand.java
  src/main/java/seedu/internship/logic/parser/CopyCommandParser.java
  src/main/java/seedu/internship/logic/parser/InternBuddyParser.java
  src/main/java/seedu/internship/model/InternBuddy.java
  src/main/java/seedu/internship/model/Model.java
  src/main/java/seedu/internship/model/ModelManager.java
  src/test/java/seedu/internship/logic/commands/AddCommandTest.java
  src/test/java/seedu/internship/logic/commands/CopyCommandTest.java
  src/test/java/seedu/internship/logic/parser/CopyCommandParserTest.java
  src/test/java/seedu/internship/logic/parser/InternBuddyParserTest.java
Labels: refactor, priority.High

#131 Update indexing error
  src/main/java/seedu/internship/commons/core/Messages.java
  src/main/java/seedu/internship/commons/util/StringUtil.java
  src/main/java/seedu/internship/logic/commands/EditCommand.java
  src/main/java/seedu/internship/logic/commands/FindCommand.java
  src/main/java/seedu/internship/logic/commands/ViewCommand.java
  src/main/java/seedu/internship/logic/parser/EditCommandParser.java
  src/main/java/seedu/internship/logic/parser/ParserUtil.java
  src/main/java/seedu/internship/logic/parser/ViewCommandParser.java
  src/test/java/seedu/internship/commons/util/StringUtilTest.java
  src/test/java/seedu/internship/logic/commands/EditCommandTest.java
  src/test/java/seedu/internship/logic/commands/ViewCommandTest.java
  src/test/java/seedu/internship/logic/parser/EditCommandParserTest.java
Labels: type.Enhancement

#133 Update indexing copy delete
  src/main/java/seedu/internship/logic/commands/CopyCommand.java
  src/main/java/seedu/internship/logic/commands/DeleteIndexCommand.java
  src/main/java/seedu/internship/logic/commands/FindCommand.java
  src/main/java/seedu/internship/logic/parser/CopyCommandParser.java
  src/main/java/seedu/internship/logic/parser/DeleteIndexCommandParser.java
  src/test/java/seedu/internship/logic/LogicManagerTest.java
  src/test/java/seedu/internship/logic/commands/CopyCommandTest.java
  src/test/java/seedu/internship/logic/commands/DeleteIndexCommandTest.java
  src/test/java/seedu/internship/logic/parser/CopyCommandParserTest.java
  src/test/java/seedu/internship/logic/parser/DeleteIndexCommandParserTest.java
Labels: type.Enhancement

#132 Fix Help Window and Minor Issues
  src/main/java/seedu/internship/logic/commands/CopyCommand.java
  src/main/java/seedu/internship/model/InternBuddy.java
  src/main/java/seedu/internship/model/internship/Status.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.High

#127 Update Documents
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/help-window-changes.png
  docs/images/ui-changes.png
  docs/index.md
  docs/team/eugenetangkj.md
  internbuddy.json
  src/main/java/seedu/internship/model/util/SampleDataUtil.java
  src/test/java/seedu/internship/model/util/SampleDataUtilTest.java
Labels: documentation, priority.High

#137 Update DeleteFieldCommand
  src/main/java/seedu/internship/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/internship/logic/commands/DeleteIndexCommand.java
  src/main/java/seedu/internship/logic/commands/FindCommand.java
  src/main/java/seedu/internship/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/internship/logic/parser/DeleteIndexCommandParser.java
Labels: type.Enhancement, priority.High

#138 Update date label in InternshipCard
  src/main/java/seedu/internship/ui/InternshipCard.java
  src/test/java/seedu/internship/ui/InternshipCardTest.java
Labels: type.Enhancement, priority.Medium

#143 Fix delete command
  src/main/java/seedu/internship/logic/parser/DeleteFieldCommandParser.java
Labels: bug, priority.High

#144 Command history
  src/main/java/seedu/internship/storage/CommandHistory.java
  src/main/java/seedu/internship/ui/CommandBox.java
  src/test/java/seedu/internship/storage/CommandHistoryTest.java
Labels: type.story, type.Enhancement, priority.Medium

#142 Check 1: Fix message consistencies
  src/main/java/seedu/internship/commons/core/Messages.java
  src/main/java/seedu/internship/logic/commands/AddCommand.java
  src/main/java/seedu/internship/logic/commands/CopyCommand.java
  src/main/java/seedu/internship/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/internship/logic/commands/DeleteIndexCommand.java
  src/main/java/seedu/internship/logic/commands/EditCommand.java
  src/main/java/seedu/internship/logic/commands/FindCommand.java
  src/main/java/seedu/internship/logic/commands/UpcomingCommand.java
  src/main/java/seedu/internship/logic/commands/ViewCommand.java
Labels: type.Enhancement, priority.Medium

#149 Update ug command history
  docs/UserGuide.md
  docs/images/ug-find-example.png
  src/main/java/seedu/internship/storage/CommandHistory.java
  src/main/java/seedu/internship/ui/CommandBox.java
Labels: documentation

#148 Check 2: Check user guide for v1.3
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/github-raw.png
  docs/images/internbuddy-json-sample.png
  docs/images/ug-add-example.png
  docs/images/ug-appendix-b-json-example.png
  docs/images/ug-edit-example.png
  docs/images/ug-help-window.png
  docs/images/ug-navigate-commands.png
  docs/index.md
Labels: documentation, priority.High
